# a619484ea9c28e5418df.a2ab5797ab613681ee129c07f1f8b9510979575d632e966b377dbcb457e33fd08790ab1d3bca5d14e35e0b9b3e58e6e542ef9f3e7365391f7964bfb39a19c433

# Example workflow using Arm Virtual Hardware (AVH) target
# See https://avh.arm.com for more info
# 
# You will need an Arm Virtual Hardware login to run successfully
# To generate API_TOKEN, go to Profile > API > Generate in AVH browser window.
# Recommended to specify as API_TOKEN secret
#
# Example Project in Projects/B-U585I-IOT02A/Demonstrations/IOT_HTTP_WebServer/
# Built offline
#
# See also scripts/avh directory

name: Rebuild and run STM32U5 Webserver

on:
    push:
    # pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

jobs:
    avh-test:
        runs-on: ubuntu-latest
        env:
          ENDPOINT: https://app.avh.arm.com/api   
          API_TOKEN: ${{ secrets.API_TOKEN }}   
        steps:
          - name: clone repo
            uses: actions/checkout@v2
                                    
          - name: Get OpenVPN websockets and other dependencies
            run: |
                sudo apt-get -y update
                sudo apt -y install openvpn sshpass curl jq
                pip install websockets asyncio

          - name: install npm
            uses: actions/setup-node@v3
            with:
              node-version: 16
              
          - name: sensor demo
            run: |
              pwd
              cp .github/workflows/example-sensor-test.js .
              cp Projects/B-U585I-IOT02A/Demonstrations/IOT_HTTP_WebServer/MDK-ARM/STM32CubeU5_Demo_U585I-IOT02A/Exe/STM32CubeU5_Demo_U585I-IOT02A.axf ./demo.axf
              npm example-sensor-test.js

          # - name: pull avhcli utility
            # run: |
              # echo need to update repo link when available
              # # git clone https://github.com/ARM-software/avhcli.git
              # git clone https://github.com/RonanSynnottArm/avhcli.git

          # - name: Create [${{ env.INSTANCE1 }}] on AVH
            # run: |
              # avhcli/avhcli.sh -t $API_TOKEN -n $INSTANCE1 -m $MODEL create
              # avhcli/avhcli.sh -t $API_TOKEN -n $INSTANCE1 -m $MODEL start

          # - name: connect to AVH OpenVPN
            # run: |
              # sudo openvpn --config avhcli/avh.ovpn --daemon 
              # echo Connecting and ping-ing instances...
              # while ! ping -c 1 $(cat "./avhcli/${{ env.INSTANCE1 }}_lan_ip.txt"); do
                # echo .
                # sleep 1
              # done
              # echo Connected

          # - name: scp binaries to ${{ env.INSTANCE1 }}
            # run: |
              # sshpass -p raspberry scp -o StrictHostKeyChecking=no ${{ env.INSTANCE1 }} pi@$(cat "./avhcli/${{ env.INSTANCE1 }}_lan_ip.txt"):~/
              # sshpass -p raspberry ssh -o StrictHostKeyChecking=no pi@$(cat "./avhcli/${{ env.INSTANCE1 }}_lan_ip.txt") chmod 755 ${{ env.INSTANCE1 }}
              
          - name: chmod 755 python scripts
            run: chmod 755 avhcli/ws.py
            
              # chmod 755 scripts/avh/ws.py
              # chmod 755 scripts/avh/web_socket_light_test.py
              # chmod 755 scripts/avh/web_socket_chip_tool_test.py
              # chmod 755 avhcli/ws.py

          # - name: Start webserver on ${{ env.INSTANCE1 }} via WebSocket to console
            # run: |
              # ./scripts/avh/web_socket_chip_tool_test.py $(cat "./avhcli/${{ env.INSTANCE1 }}_console.txt")

          - name: install npm
            uses: actions/setup-node@v3
            with:
              node-version: 16
              
          - name: sensor demo
            run:  node .github/workflows/example-sensor-test.js

          - name: Stopping/Deleting ${{ env.INSTANCE1 }}
            run: | 
              # sudo killall openvpn
              avhcli/avhcli.sh -t $API_TOKEN -n $INSTANCE1 -m $MODEL delete
              # avhcli/avhcli.sh -t $API_TOKEN -n $INSTANCE1 -m $MODEL stop
